In [2]:
# Importing Libraries

import numpy as np
import pandas as pd

# Question 1: What's the version of NumPy that you installed?

np.__version__

# Ans: 1.21.5

'1.21.5'

In [3]:
# Reading the data from GitHub

data=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [11]:
# Displaying the data

data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
# Question 2: How many records are in the dataset? Rows

data.shape

# Ans: 11914

(11914, 16)

In [10]:
# Question 3: Who are the most frequent car manufacturers (top-3) according to the dataset?

data["Make"].value_counts(ascending=False)

# Ans: Chevrolet, Ford, Volkswagen

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [25]:
# Question 4: What's the number of unique Audi car models in the dataset?

data[data["Make"] == "Audi"].Model.nunique()

# Ans: 34

34

In [40]:
# Question 5: How many columns in the dataset have missing values?

data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [53]:
# Question 6: 
# 1. Find the median value of "Engine Cylinders" column in the dataset.

print("Median of ENgine Cylinders is:", data["Engine Cylinders"].median())

# 2. Next, calculate the most frequent value of the same "Engine Cylinders".

print("Most frequent value in Engine Cycliners is:", data["Engine Cylinders"].mode())

# 3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
data["Engine Cylinders"].fillna(data["Engine Cylinders"].mode()[0], inplace=True)


#  4. Now, calculate the median value of "Engine Cylinders" once again.
print("Median of Engine Cylinders after filling missing values with mode is:", data["Engine Cylinders"].median())

# Ans: No

Median of ENgine Cylinders is: 6.0
Most frequent value in Engine Cycliners is: 0    4.0
Name: Engine Cylinders, dtype: float64
Median of Engine Cylinders after filling missing values with mode is: 6.0


In [58]:
# Question 7:

# 1. Select all the "Lotus" cars from the dataset.

Lotus_data=data[data["Make"] == "Lotus"]
Lotus_data

Make      Model  Year                Engine Fuel Type  Engine HP  \
3912  Lotus      Elise  2009     premium unleaded (required)      189.0   
3913  Lotus      Elise  2009     premium unleaded (required)      218.0   
3914  Lotus      Elise  2009     premium unleaded (required)      189.0   
3915  Lotus      Elise  2010     premium unleaded (required)      189.0   
3916  Lotus      Elise  2010     premium unleaded (required)      218.0   
3917  Lotus      Elise  2011     premium unleaded (required)      189.0   
3918  Lotus      Elise  2011     premium unleaded (required)      217.0   
3919  Lotus      Elise  2011     premium unleaded (required)      217.0   
4216  Lotus     Esprit  2002     premium unleaded (required)      350.0   
4217  Lotus     Esprit  2003     premium unleaded (required)      350.0   
4218  Lotus     Esprit  2004     premium unleaded (required)      350.0   
4257  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4258  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4259  Lotus      Evora  2011     premium unleaded (required)      276.0   
4260  Lotus      Evora  2011     premium unleaded (required)      276.0   
4261  Lotus      Evora  2013     premium unleaded (required)      276.0   
4262  Lotus      Evora  2013     premium unleaded (required)      345.0   
4263  Lotus      Evora  2013     premium unleaded (required)      345.0   
4264  Lotus      Evora  2013     premium unleaded (required)      276.0   
4265  Lotus      Evora  2014     premium unleaded (required)      345.0   
4266  Lotus      Evora  2014     premium unleaded (required)      276.0   
4267  Lotus      Evora  2014     premium unleaded (required)      345.0   
4268  Lotus      Evora  2014     premium unleaded (required)      276.0   
4292  Lotus      Exige  2009  premium unleaded (recommended)      257.0   
4293  Lotus      Exige  2009  premium unleaded (recommended)      240.0   
4294  Lotus      Exige  2010  premium unleaded (recommended)      240.0   
4295  Lotus      Exige  2011  premium unleaded (recommended)      240.0   
4296  Lotus      Exige  2011  premium unleaded (recommended)      257.0   
4297  Lotus      Exige  2011  premium unleaded (recommended)      257.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   
3917               4.0            MANUAL  rear wheel drive              2.0   
3918               4.0            MANUAL  rear wheel drive              2.0   
3919               4.0            MANUAL  rear wheel drive              2.0   
4216               8.0            MANUAL  rear wheel drive              2.0   
4217               8.0            MANUAL  rear wheel drive              2.0   
4218               8.0            MANUAL  rear wheel drive              2.0   
4257               6.0            MANUAL  rear wheel drive              2.0   
4258               6.0            MANUAL  rear wheel drive              2.0   
4259               6.0            MANUAL  rear wheel drive              2.0   
4260               6.0            MANUAL  rear wheel drive              2.0   
4261               6.0            MANUAL  rear wheel drive              2.0   
4262               6.0            MANUAL  rear wheel drive              2.0   
4263               6.0            MANUAL  rear wheel drive              2.0   
4264               6.0            MANUAL  rear wheel drive              2.0   
4265               6.0            MANUAL  rear wheel drive              2.0   
4266               6.0            MANUAL  rear wheel drive              2.0   
4267              

In [64]:
# 2. Select only columns "Engine HP", "Engine Cylinders".
Lotus_data[["Engine HP", "Engine Cylinders"]]

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [65]:
# 3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

Lotus_data[["Engine HP", "Engine Cylinders"]].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [68]:
# 4. Get the underlying NumPy array. Let's call it X.

X= Lotus_data[["Engine HP", "Engine Cylinders"]].drop_duplicates()
X

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [113]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX

XTX=X.T.dot(X)
XTX

Engine HP  Engine Cylinders
Engine HP          731684.0           13410.0
Engine Cylinders    13410.0             252.0

In [114]:
# 6. Invert XTX.

Inv_XTX = np.linalg.inv(XTX)
Inv_XTX    ?NUM3

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [89]:
# 7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

y=np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [115]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w=Inv_XTX.dot(X.T.dot(y))
w

# Ans: 4.5949

array([  4.59494481, -63.56432501])

# Breaking Linear Regression Equation as follows: 
## Inverse(XTranspose * X) * (XTranspose * y)

In [116]:
num1=X.T
num1

3912   3913   3918   4216   4257   4259   4262   4292  \
Engine HP         189.0  218.0  217.0  350.0  400.0  276.0  345.0  257.0   
Engine Cylinders    4.0    4.0    4.0    8.0    6.0    6.0    6.0    4.0   

                   4293  
Engine HP         240.0  
Engine Cylinders    4.0

In [105]:
num2=num1.dot(X)
num2

Engine HP  Engine Cylinders
Engine HP          731684.0           13410.0
Engine Cylinders    13410.0             252.0

In [107]:
num3=np.linalg.inv(num2)
num3

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [109]:
num4=num1.dot(y)
num4

Engine HP           2509650.0
Engine Cylinders      45600.0
dtype: float64

In [111]:
w=num3.dot(num4)
w

array([  4.59494481, -63.56432501])